######################## default configuration ####################
baseURL = "https://tophouseplans.netlify.app"
title = "Top House Plans"
theme = "jala"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "5"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

############################# output ##############################
[outputs]
home = [ "HTML", "RSS", "json"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


################################ menu ##################################
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about"
weight = 2






[[menu.main]]
name = "Contact"
url = "contact"
weight = 3

[[menu.main]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4

[[menu.main]]
name = "DMCA"
url = "dmca"
weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Top House Plans"
author = ""

# search  
search = true
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright
copyright = "Copyright 2021 Top House Plans](https://tophouseplans.netlify.app)"


# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[params.cookies]
enable = true
expire_days = 2
